title: My Data Privacy Book
author: John Doe
theme: jekyll-theme-cayman
markdown: kramdown

# Optional configuration for jekyll-theme-cayman theme
jekyll-theme-cayman:
  # Enable or disable the sidebar
  sidebar:
    enabled: true

# Navigation structure
nav:
  - Home: /docs/index.md
  - Chapter 1: /docs/chapter1.md
  - Chapter 2: /docs/chapter2.md
  - Chapter 3: /docs/chapter3.md
  - License: LICENSE.md
