title: My Data Privacy Book
author: Ertuğrul Akçaoğlu
theme: just-the-docs
markdown: kramdown

# Optional configuration for just-the-docs theme
just-the-docs:
  logo: "/assets/images/logo.png"
  search_enabled: true
  search:
    heading_level: 2
