title: My Data Privacy Book
author: John Doe
theme: just-the-docs
markdown: kramdown

# Optional configuration for just-the-docs theme
just-the-docs:
  logo: "/assets/images/logo.png"
  search_enabled: true
  search:
    heading_level: 2

# Navigation structure
nav:
  - Home: index.md
  - Chapter 1: chapter1.md
  - Chapter 2: chapter2.md
  - Chapter 3: chapter3.md
