site_name: My Data Privacy Book (Tesitng...)

# Theme configuration
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Chapter 1: chapter1.md
  - Chapter 2: chapter2.md
  - Chapter 3: chapter3.md
  - Licence: LICENSE.md
